### ISSUE TITLE
分发器：企业微信分发部门ID参数不定

### ISSUE THREAD

**Issue by howie6879** [howie6879/2c#16]
问题：

> 企业微信分发的`toparty`参数不一定总是为1，需要自动获取。有的可能为2

![image](https://user-images.githubusercontent.com/17047388/147326382-b040ca8a-1b4f-475d-afa7-f1cc14a5a444.png)

**Comment by zyd16888** [comment]
多部门是否要考虑在内，如下情况。
```
{'errcode': 0, 'errmsg': 'ok', 'department': [{'id': 2, 'name': '公众号消息推送', 'parentid': 1, 'order': 100000000, 'department_leader': []}, {'id': 3, 'name': '签到消息推送', 'parentid': 1, 'order': 99999000, 'department_leader': []}, {'id': 5, 'name': 'epic推送', 'parentid': 1, 'order': 99997000, 'department_leader': []}]}
```

或者是否可以考虑，不使用部门做区分，直接使用 `touser: @all` 参数。

**Comment by howie6879** [comment]
@zyd16888 我觉得当前部门分发支持不变，然后用户定了toparty就用用户定的，我没有定就自动获取

对于`touser`，可以考虑再增加一个函数来针对这个分发情况，然后默认发部门，用户可定义发`touser`

两种方式都支持。

**Comment by zyd16888** [comment]
开始修复了，看空闲时间，最晚一周处理完（我尽量快些）。

**Comment by howie6879** [comment]
Fixed by #21
